/*
 * <h1>Traveler interface</h1>.
 * This interface implements the Traveler interface for the user, and to enable the user access all the feature of the system .
 * You can run the interface from here 
 * <p>
 */
package pkg251project;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author msmil
 */
public class Travelus extends javax.swing.JFrame {

    /**
     * Creates new form Travelus
     */
    Traveler travlog = null;
    int counter;
    String username11, pass11, email11, phone;
    char gender;
    static ArrayList<Flights> f = null;

    /**
     *
     * @param f Array list of flights that links the traveler to its flights
     */
    public Travelus(ArrayList<Flights> f) {
        initComponents();
        setLocationRelativeTo(null);
        this.f = f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        changePass = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Strat = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);
        jPanel1.add(name);
        name.setBounds(200, 240, 110, 26);

        jLabel3.setBackground(new java.awt.Color(175, 167, 144));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/rsz_output-onlinepngtools_13.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 90, 130, 70);

        jLabel8.setBackground(new java.awt.Color(153, 153, 153));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Password");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(110, 270, 100, 30);

        jLabel9.setBackground(new java.awt.Color(175, 167, 144));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Travelus");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(190, 160, 70, 30);

        jLabel11.setBackground(new java.awt.Color(175, 167, 144));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Username/Email");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 240, 130, 30);

        changePass.setBackground(new java.awt.Color(175, 167, 144));
        changePass.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        changePass.setForeground(new java.awt.Color(204, 204, 204));
        changePass.setText("Forget password? Click here");
        changePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePassMouseClicked(evt);
            }
        });
        jPanel1.add(changePass);
        changePass.setBounds(210, 290, 180, 30);

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Don't have account?");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(160, 410, 130, 30);

        Strat.setText("Sign up");
        Strat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StratActionPerformed(evt);
            }
        });
        jPanel1.add(Strat);
        Strat.setBounds(170, 440, 90, 29);

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Start as a guest ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(170, 460, 130, 30);

        jButton3.setText("Start");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(170, 490, 90, 29);

        jButton2.setText("Log in");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(200, 320, 90, 29);

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel1.add(pass);
        pass.setBounds(200, 270, 110, 26);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePassMouseClicked
        // TODO add your handling code here:
        getPass mm = new getPass();
        mm.setVisible(true);
        mm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_changePassMouseClicked

    private void StratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StratActionPerformed
        // TODO add your handling code here:
        SignUp sp = new SignUp();
        sp.setVisible(true);
        sp.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_StratActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        MainMenu m = new MainMenu(travlog);
        m.setVisible(true);
        m.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
//Checking username/email and password

    boolean checkData(String name, String passw) {
        boolean check = false;
        try {
            RandomAccessFile read = new RandomAccessFile("userInfo.txt", "rw");
            String line = read.readLine();
            for (int i = 0; i <= counter; i += 5) {
                if (line != null) {
                    username11 = line.substring(9);
                    email11 = read.readLine().substring(6);
                    pass11 = read.readLine().substring(9);
                    phone = read.readLine().substring(6);
                    gender = read.readLine().substring(7).charAt(0);
                    line = read.readLine();
                    line = read.readLine();
                    if ((name.equals(username11) && passw.equals(pass11.trim())) || (name.equals(email11) && passw.equals(pass11.trim()))) {
                        JOptionPane.showMessageDialog(null, "Logined successfully");
                        travlog = new Traveler(username11, gender, email11, pass11.trim(), phone, null);
                        check = true;
                        break;
                    } else {
                        check = false;
                        travlog = null;
                    }
                }
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Travelus.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Travelus.class.getName()).log(Level.SEVERE, null, ex);
        }
        return check;
    }

    /**
     *
     * @param travlog object from the traveler class
     */
    public void setTravlog(Traveler travlog) {
        this.travlog = travlog;
    }

    /**
     *
     * @return the object of the traveler class
     */
    public Traveler getTravlog() {
        return travlog;
    }

    void readFile() {
        try {

            FileReader fw = new FileReader("userInfo.txt");
        } catch (FileNotFoundException ex) {

            try {
                FileWriter f = new FileWriter("userInfo.txt");
            } catch (IOException ex1) {
                Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex1);
            }

        }

    }

    void countLines() {

        try {
            counter = 1;
            RandomAccessFile read = new RandomAccessFile("userInfo.txt", "rw");
            while (read.readLine() != null) {
                counter++;

            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        readFile();
        countLines();
        if (checkData(name.getText(), pass.getText())) {
            MainMenu mm = new MainMenu(travlog);
            mm.setVisible(true);
            mm.setLocationRelativeTo(null);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Username/password is wrong");
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Travelus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Travelus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Travelus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Travelus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Travelus(f).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Strat;
    private javax.swing.JLabel changePass;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField pass;
    // End of variables declaration//GEN-END:variables
}
